### ISSUE TITLE
Will this work on raspberry pi instead of Arduino?

### ISSUE THREAD

**Issue by ditchfieldcaleb** [Yveaux/NRF24_Sniffer#4]
Hi, I apologize if this is a very basic question. Can I get this software to work on a Raspberry pi hooked up to the NRF24l01+ via SPI instead of Arduino?

**Comment by Yveaux** [comment]
Then you have to port the Arduino sniffer sketch to Raspberry Pi, and also convert the accompanying Windows application to Raspberry Pi.
Not impossible, but not easy either.
