### ISSUE TITLE
Won't compile for ESP8266

### ISSUE THREAD

**Issue by EPNW** [Yveaux/NRF24_Sniffer#6]
The way interrupts are enabled and disabled in `CircularBuffer.h` is not supported by the ESP8266 (`SREG` not defined). Maybe exchange this with Arduinos `noInterrputs()` and `interrupts()` methods?

**Comment by bilogic** [comment]
1. Were you successfully in using ```noInterrupts()``` and ```interrupts()```?
2. Which ESP8266 pin did you connect to NRF24's IRQ?

**Comment by Yveaux** [comment]
It won't work as Arduino's ESP port does not support SPI transactions completely -- see here https://github.com/mysensors/MySensors/issues/1128
